# Generated by Django 4.2.13 on 2026-06-17 01:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['risk_level'], name='geoapp_risk_risk_le_b7d732_idx')],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('school', 'School'), ('cafe', 'Cafe'), ('pharmacy', 'Pharmacy'), ('police', 'Police'), ('fire_station', 'Fire Station'), ('parking', 'Parking'), ('other', 'Other')], default='other', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('risk_confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='geoapp_poi_categor_1813bd_idx')],
            },
        ),
    ]
